version: '2.1'
services:
  bot:
    build: ./bot
    env_file: .app_env
    volumes:
      - ./bot:/code
      - ~/.telegram-channels-feed/bot:/data
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  sender:
    build: ./sender
    env_file: .app_env
    environment:
      - JAVA_OPTS=-Xmx256M -Xms256M
    mem_limit: 512mb
    volumes:
      - ~/.telegram-channels-feed/sender:/tmp
    depends_on:
      db:
        condition: service_healthy
      rabbit:
        condition: service_healthy
    restart: unless-stopped

  tg:
    build: ./tg
    env_file: .app_env
    environment:
      - JAVA_OPTS=-Xmx256M -Xms256M
    mem_limit: 512mb
    volumes:
      - ~/.telegram-channels-feed/tg:/tmp
    depends_on:
      db:
        condition: service_healthy
      rabbit:
        condition: service_healthy
    restart: unless-stopped

  db:
    build: ./init/db
    volumes:
      - ~/.telegram-channels-feed/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  rabbit:
    build: ./init/rabbit
    hostname: rabbit
    volumes:
      - ~/.telegram-channels-feed/rabbitmq:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: unless-stopped
