version: '2.1'
services:
  bot:
    build: ./bot
    volumes:
      - ./bot:/code
      - ./storage/bot:/data
    depends_on:
      tg-cli:
        condition: service_healthy
      db:
        condition: service_healthy
      rabbit:
        condition: service_healthy
    restart: unless-stopped
  tg-cli:
    build: ./tg-cli
    volumes:
      - ./storage/tg-cli:/telegram
    ports:
      - "4458:4458"
    depends_on:
      rabbit:
        condition: service_healthy
    restart: unless-stopped
  db:
    image: "healthcheck/postgres:alpine"
    volumes:
      - ./storage/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
  rabbit:
    image: "rednblack/rabbitmq"
    hostname: rabbit
    volumes:
      - ./storage/rabbitmq:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: unless-stopped
