spring:
  main:
    web-environment: false
  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: Europe/Moscow
    date-format: yyyy-MM-dd'T'HH:mm:ssZ
  cloud:
    stream:
      bindings:
        input:
          group: raw
          destination: channels_feed.raw
          content-type: application/json
        output:
          producer:
            required-groups:
              - processed
          destination: channels_feed.processed
          content-type: application/json

processor:
  bot-token: ${CF_BOT_TOKEN}
  tg-cli-url: ${CF_TGCLI_URL}

logging:
  root:
    level: INFO
