spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: Europe/Moscow
    date-format: yyyy-MM-dd'T'HH:mm:ssZ
  cloud:
    stream:
      bindings:
        output:
          producer:
            required-groups:
              - posts
          destination: channels_feed.posts
          content-type: application/json

tg:
  api-id:
  api-hash:
  number:
  model: desktop
  app-version: 0.0.1
  sys-version: 0.0.1
  lang-code: en
  storage-path: ${user.home}/.telegram-channels-feed
