spring:
  application:
    name: tg
  rabbitmq:
    url: ${CF_RABBIT_URL}
  cloud:
    stream:
      bindings:
        output:
          producer:
            required-groups:
              - posts
          destination: channels_feed.posts
          content-type: application/json
  datasource:
    url: jdbc:${CF_DB_URL}

tg:
  api-id: ${CF_TG_API_ID}
  api-hash: ${CF_TG_API_HASH}
  phone-number: ${CF_TG_NUMBER}
  model: Bot
  app-version: ${VERSION}
  sys-version: ${VERSION}
  lang-code: en
  storage-path: ${user.home}/.telegram-channels-feed/tg

processing:
  channels-interval-min: 60
  channels-interval-max: 120
  channels-interval-time-unit: SECONDS
  posts-batch-size: 50
  posts-interval-min: 5
  posts-interval-max: 15
  posts-interval-time-unit: SECONDS
