spring:
  application:
    name: tg
  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: Europe/Moscow
    date-format: yyyy-MM-dd'T'HH:mm:ssZ
  cloud:
    stream:
      bindings:
        output:
          producer:
            required-groups:
              - posts
          destination: channels_feed.posts
          content-type: application/json

tg:
  api-id: ${CF_TG_API_ID}
  api-hash: ${CF_TG_API_HASH}
  phone-number: ${CF_TG_NUMBER}
  model: Bot
  app-version: ${VERSION}
  sys-version: ${VERSION}
  lang-code: en
  storage-path: ${java.io.tmpdir}/tg

processing:
  channels-batch-size: 10
  posts-batch-size: 50
  posts-interval-min: 10
  posts-interval-max: 60
  posts-interval-time-unit: SECONDS
